# Generated by Django 4.2.4 on 2023-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_invoice_address_invoice_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
